workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
    scripts:
      - name: Setup Android Project
        script: |
          flutter create . --platforms=android
          # minSdkVersion 21 সেট করা
          sed -i '' 's/minSdkVersion = flutter.minSdkVersion/minSdkVersion = 21/g' android/app/build.gradle.kts || true
          sed -i '' 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle || true
      - name: Build Android APK
        script: |
          flutter build apk --release
    artifacts:
      - build/**/outputs/**/*.apk
