workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini_m2
    max_build_duration: 30
    environment:
      flutter: stable
      android_build_tools: 34.0.0
    scripts:
      - name: Create and Configure Android
        script: |
          flutter create . --platforms=android
          # minSdkVersion ও compileSdkVersion ফিক্স
          sed -i '' 's/minSdkVersion = flutter.minSdkVersion/minSdkVersion = 21/g' android/app/build.gradle.kts || true
          sed -i '' 's/minSdkVersion flutter.minSdkVersion/minSdkVersion 21/g' android/app/build.gradle || true
          sed -i '' 's/compileSdkVersion = flutter.compileSdkVersion/compileSdkVersion = 34/g' android/app/build.gradle.kts || true
          sed -i '' 's/compileSdkVersion flutter.compileSdkVersion/compileSdkVersion 34/g' android/app/build.gradle || true
      - name: Build Android APK
        script: |
          flutter build apk --release --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
